# Generated by Django 4.2 on 2023-04-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('vk', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfBillets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
